# Generated by Django 5.0.3 on 2024-04-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_customer_table_alter_store_image_customuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
