# Generated by Django 5.0.3 on 2024-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, default='Tokyo, Japan', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/default_image.png', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unavailable_dates',
            field=models.ManyToManyField(blank=True, related_name='unavailable_product', to='nagoyameshi.date'),
        ),
    ]
