# Generated by Django 5.0.3 on 2024-04-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='available_dates',
            field=models.ManyToManyField(blank=True, to='nagoyameshi.date'),
        ),
    ]
