# Generated by Django 5.0.3 on 2024-04-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0006_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='available_dates',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='StoreDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagoyameshi.dayoff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeday_offs', to='nagoyameshi.store')),
            ],
        ),
    ]
