# Generated by Django 5.0.3 on 2024-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0007_dayoff_remove_store_available_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='available_dates',
            field=models.ManyToManyField(to='nagoyameshi.date'),
        ),
    ]
