# Generated by Django 5.0.3 on 2024-04-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0008_store_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='unavailable_dates',
            field=models.ManyToManyField(blank=True, related_name='unavailable_stores', to='nagoyameshi.date'),
        ),
        migrations.AlterField(
            model_name='store',
            name='available_dates',
            field=models.ManyToManyField(blank=True, related_name='available_stores', to='nagoyameshi.date'),
        ),
    ]
