# Generated by Django 5.0.3 on 2024-04-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0009_store_unavailable_dates_alter_store_available_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='available_dates',
        ),
    ]
